##MAX PLAYERS IN TEAM
maxPlayersPerTeam: 8

##CHANGE TEAM NAMES
attackersTeamName: Attackers
defendersTeamName: Defenders

##ADJUST COINS PER KILL AND WIN
coins-on-win: 3
coins-on-kill: 1

### ADJUST KING HEALTH NOTE IT SHOULD BE WITH ONE DECIMAL EXAMPLE : 80.0
king-health: 30.0
king-name: Marcus III

## ADJUST BOMBARDIER KIT TNT COOLDOWN IN SECONDS TO YOUR NEEDS
tntCooldown: 30
wizardAttackSpellCooldown: 45
wizardSupportSpellCooldown: 60

## ADJUST TNT DAMAGE TO PLAYERS TNT CANNOT DAMAGE KING
tntDamage: 7.0
## 7.0 damage = 2 hearts

##DO NOT TOUCH ##THIS CAN DEGRADE SERVER PERFORMANCE ON MAP REGENERATION IF YOUR SERVER IS LAGGING WHILE
##MAP IS REGENERATING LOWER THIS NUMBER
##IF YOU THINK MAP REGENERATION IS TO SLOW TRY INCREASING IT TO 5000 BUT BE AWARE THAT IT CAN RUIN SERVER PERFORMANCE
##WHILE REGENERATING
arenaBlockRegenPerSecond: 3000
